version: '3.8'

services:
  backend:
    container_name: hero-backend
    build:
      context: /mnt/c/Users/felip/GolandProjects/webskt/chatapp
    volumes:
      - /mnt/c/Users/felip/GolandProjects/webskt/chatapp:/app
    working_dir: /app
    ports:
      - "3333:3333"
    command: sh -c "npm install && npm run dev"
    networks:
      - hero-network

  frontend:
    container_name: hero-frontend
    build:
      context: /mnt/c/Users/felip/projectship/hero-geometric
    volumes:
      - /mnt/c/Users/felip/projectship/hero-geometric:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - hero-network

  mysql:
    image: mysql:8.0
    container_name: hero-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hero
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hero-network

volumes:
  db_data:

networks:
  hero-network:
    driver: bridge
