# Dockerfile.prod (frontend)
FROM node:20-alpine as builder

WORKDIR /app

COPY . .

RUN pnpm install
RUN pnpm run build

# Production image
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "start"]

